### ISSUE TITLE
Node process is not properly killed

### ISSUE THREAD

**Issue by sharokh1** [nesk/rialto#10]
It should be possible to fetch the PID of the process running by rialto.. I think there is a method for it but it is not accessible.

**Comment by nesk** [comment]
While writing the initial basecode of Rialto, I've added a method to get the process PID but removed it later because the library should be smart enough to manage its own Node process.

Rialto's goal is to provide a complete abstraction over the PHP/Node communication, providing a method to get the process PID would ruin this abstraction because the process could be killed (or whatever else) by the developer.

However, before rejecting the idea, maybe could you tell me why you need the PID? What will you do with it? If it's only for debugging purposes, you can already get the PID [through a logger](https://github.com/nesk/rialto/blob/master/docs/api.md#options). 😉

**Comment by sharokh1** [comment]
Thank you for responding.
My php application launches a node process and I need to have the possibility to kill the node process without killing php. Maybe I'm doing something wrong but sometimes the node process keeps living.

**Comment by nesk** [comment]
Then we should consider this as a bug. I will need some informations to help you:

- Preferably, a code reproducing the bug on all executions, but if you can't manage to create one then extract the code directly from your application (please, strip anything useless for me).
- Provide the logs generated by your example, see how to get them [in PuPHPeteer's guidelines](https://github.com/nesk/puphpeteer/blob/master/.github/contributing.md#provide-logs-with-your-bug-report).
- What is your environment? OS (+ version), Node version, and PHP version.
- Which package manager are you using? NPM? Yarn ? Other?
- Are you using NVM? Which version?

If you have some additional context, please provide it.

**Comment by sharokh1** [comment]
Before we are sure its a bug and I deliver what you asked, is there a way to stop a process ? I do not think it should be complicated. I think I'm doing something wrong. I'm using your puppeteer wrapper and when I want to stop the process im doing the following.
`     $this->browser->close();
        unset($this->page);
        unset($this->browser);
        unset($this->puppeteer); `

**Comment by nesk** [comment]
@sharokh1 Anything new?

**Comment by sharokh1** [comment]
Hi, sorry for not replying earlier!
When the resources are unset, the puppeteer (node) process continuous to run in the background.
To fix this, we made sure the php process is killed. This way all the relevant processes will also be killed.

**Comment by nesk** [comment]
So, should I consider this issue as fixed?
 
If you want, you can provide me with a code reproducing the bug, and I can try by myself to see what’s the cause of this.

**Comment by nesk** [comment]
Closing since the issue is inactive.
